INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (0, '{"vn":"Cá Ốc Sên","en":"Snail fish"}', 5, 2, 2, 55, 15, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (1, '{"vn":"Cá Cỏ Xanh","en":"Green Grass"}', 5, 2, 2, 60, 25, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (2, '{"vn":"Cá Cỏ Vàng","en":"Golden Grass"}', 5, 3, 3, 80, 32, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (3, '{"vn":"Cá Mắt Lớn","en":"Big Eye"}', 5, 4, 4, 70, 43, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (4, '{"vn":"Cá Dẹp Vàng","en":"Goldfish"}', 5, 5, 5, 80, 54, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (5, '{"vn":"Cá Chú Hề","en":"Fish Sticky"}', 5, 6, 6, 90, 70, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (6, '{"vn":"Cá Nhỏ","en":"Small fish"}', 5, 8, 8, 90, 40, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (7, '{"vn":"Cá Xanh","en":"Green fish"}', 5, 9, 9, 120, 55, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (8, '{"vn":"Cá Đèn Lồng","en":"Fish Lantern"}', 5, 10, 10, 150, 47, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (9, '{"vn":"Cá Đèn Lồng Xanh","en":"Blue Lanterns"}', 5, 12, 12, 110, 112, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (10, '{"vn":"Rùa Biển","en":"Sea turtle"}', 4, 15, 15, 145, 80, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (11, '{"vn":"Cá Cánh Hoa","en":"Fish Flower"}', 4, 18, 18, 120, 150, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (12, '{"vn":"Cá Bướm","en":"Butterfly fish"}', 4, 20, 20, 180, 70, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (13, '{"vn":"Cá Khổng Tước","en":"Confucius Fish"}', 4, 25, 25, 255, 88, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (14, '{"vn":"Cá Kiếm","en":"Swordfish"}', 4, 30, 30, 250, 80, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (15, '{"vn":"Cá Dơi","en":"Bat Bat"}', 3, 40, 40, 180, 150, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (16, '{"vn":"Cá Mập Bạc","en":"Silver Shark"}', 3, 50, 50, 250, 90, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (17, '{"vn":"Cá Mập Vàng","en":"Shark Gold"}', 3, 75, 75, 240, 100, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (18, '{"vn":"Gậy Kim Cô","en":"Kim Coi"}', 3, 100, 100, 350, 70, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (19, '{"vn":"Cá Voi Vua","en":"Whale King"}', 1, 120, 120, 450, 150, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (20, '{"vn":"Rồng Bạc","en":"Silver Dragon"}', 2, 200, 200, 380, 110, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (21, '{"vn":"Rồng Vàng","en":"Golden Dragon"}', 2, 300, 300, 380, 110, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (22, '{"vn":"Cỏ Biển","en":"Seagrass"}', 3, 10, 20, 120, 120, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (23, '{"vn":"Đạn Nổ","en":"Bullets"}', 4, 1, 1000, 170, 180, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (24, '{"vn":"Tháp Năng Lượng","en":"Energy Tower"}', 2, 80, 120, 240, 220, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (25, '{"vn":"Cá Nhà Táng","en":"Spermaceti"}', 2, 100, 140, 250, 250, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (26, '{"vn":"Cá Tam Nguyên 3","en":"Tam Nguyen Fish 3"}', 3, 85, 95, 250, 250, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (27, '{"vn":"Cá Tam Nguyên Lớn","en":"Big Tam"}', 3, 30, 70, 130, 340, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (28, '{"vn":"Cá Tam Nguyên 4","en":"Tam Nguyen Fish 4"}', 3, 150, 170, 250, 250, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (29, '{"vn":"Cá Tử Hỉ Lớn","en":"Big Cats"}', 3, 35, 65, 360, 130, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (30, '{"vn":"Vua Cá Đỏ","en":"The Red King"}', 4, 1, 1, 170, 180, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (31, '{"vn":"Cóc xanh lè","en":"Green hook"}', 1, 100, 100, 170, 180, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (32, '{"vn":"Cóc vàng khè","en":"Yellow crane"}', 1, 200, 200, 170, 180, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (33, '{"vn":"Boss bạch tuộc đỏ","en":"Boss red octopus"}', 1, 5000, 5000, 170, 180, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (34, '{"vn":"Boss bạch tuộc vàng","en":"Boss Golden octopus "}', 2, 5000, 5000, 170, 180, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (35, '{"vn":"Boss người cá nam","en":"Boss Siren male"}', 2, 4500, 4500, 350, 70, 0);
INSERT INTO bc68.fishconfig (FishKind, FishName, Speed, FishMultiple, MaxFishMultiple, Width, Height, Deep) VALUES (36, '{"vn":"Boss người cá nữ","en":"Boss Siren"}', 2, 7500, 7500, 350, 70, 0);