/**
 * Created by quinx on 8/20/2018.
 */
module.exports = {
    GetTotalSystemGold: 1,
    GetGameStatus: 2,
    GetTopGold: 3,
    GetTopWin: 4,
    GetLogGoldUser: 5,
    GetMoneyStatus: 6,
    GetMoneyFlowStatistics: 7,
    GetGlobalBossList: 8,
    GetGlobalBossName: 9,
    UpdateGlobalBoss: 10,
    AddGlobalBoss: 11,
    DeleteGlobalBoss: 12,
    GetCCULog: 13,
    GetBroadcast: 14,
    UpdateBroadcast: 15,
    DeleteBroadcast: 16,
    AddBroadcast: 17,
    GetLogGoldUser_Redis: 18,
    GetStock: 19,
    UpdateStock: 20,
    GetEventList: 21,
    UpdateEvent: 22,
    GetEventData: 23,
    DeleteEventData: 24,
    GetUserList: 25,
    GetUserInfo: 26,
    KickUser: 27,
    GetLogUserKillBoss: 28,
    Slot_GetInfo: 29,
    GetAdminList: 30,
    GetAdminInfo: 31,
    UpdateAdminInfo: 32,
    TX_GetInfo: 33,
    Baccarat_GetInfo: 34,
    GetLogUserPlay: 35,
    XocDia_GetInfo: 36,
    VQMM_GetInfo: 37,
    ShowStore: 38,
    UpdateStoreConfig: 39,
    TXMN_GetInfo: 40,
    VQMM_AddFreeTicket: 41,
    Tracking_GameStatus: 42,
    Tracking_GetTotalReCharge: 43,
    TopDoiNap: 44,
    GetChargeInfo: 45,
    GetArticleList: 46,
    EditArticle: 47,
    AddArticle: 48,
    DeleteArticle: 49
};